# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_wrs_ipod_2', [dirname(__file__)])
        except ImportError:
            import _wrs_ipod_2
            return _wrs_ipod_2
        if fp is not None:
            try:
                _mod = imp.load_module('_wrs_ipod_2', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _wrs_ipod_2 = swig_import_helper()
    del swig_import_helper
else:
    import _wrs_ipod_2
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


WRSIPOD_EVENT_CONNECTED = _wrs_ipod_2.WRSIPOD_EVENT_CONNECTED
WRSIPOD_EVENT_DISCONNECTED = _wrs_ipod_2.WRSIPOD_EVENT_DISCONNECTED
WRSIPOD_EVENT_DETECTION_FAILED = _wrs_ipod_2.WRSIPOD_EVENT_DETECTION_FAILED
WRSIPOD_EVENT_AUTHENTICATED = _wrs_ipod_2.WRSIPOD_EVENT_AUTHENTICATED
WRSIPOD_EVENT_MODE_CHANGED = _wrs_ipod_2.WRSIPOD_EVENT_MODE_CHANGED
WRSIPOD_EVENT_PLAYSTATE_CHANGED = _wrs_ipod_2.WRSIPOD_EVENT_PLAYSTATE_CHANGED
WRSIPOD_EVENT_TRACK_CHANGED = _wrs_ipod_2.WRSIPOD_EVENT_TRACK_CHANGED
WRSIPOD_EVENT_TRACKINFO_RETRIEVED = _wrs_ipod_2.WRSIPOD_EVENT_TRACKINFO_RETRIEVED
WRSIPOD_EVENT_SAMPLERATE_RETRIEVED = _wrs_ipod_2.WRSIPOD_EVENT_SAMPLERATE_RETRIEVED
WRSIPOD_EVENT_TRACK_POSITION_CHANGED = _wrs_ipod_2.WRSIPOD_EVENT_TRACK_POSITION_CHANGED
WRSIPOD_EVENT_CHAPTER_CHANGED = _wrs_ipod_2.WRSIPOD_EVENT_CHAPTER_CHANGED
WRSIPOD_EVENT_SHUFFLE_CHANGED = _wrs_ipod_2.WRSIPOD_EVENT_SHUFFLE_CHANGED
WRSIPOD_EVENT_REPEAT_CHANGED = _wrs_ipod_2.WRSIPOD_EVENT_REPEAT_CHANGED
WRSIPOD_EVENT_PLAYLIST_CHANGED = _wrs_ipod_2.WRSIPOD_EVENT_PLAYLIST_CHANGED
WRSIPOD_EVENT_DEVICE_READY = _wrs_ipod_2.WRSIPOD_EVENT_DEVICE_READY
WRSIPOD_EVENT_UNKNOWN = _wrs_ipod_2.WRSIPOD_EVENT_UNKNOWN
WRSIPOD_PLAY_STATE_STOPPED = _wrs_ipod_2.WRSIPOD_PLAY_STATE_STOPPED
WRSIPOD_PLAY_STATE_FFW_STARTED = _wrs_ipod_2.WRSIPOD_PLAY_STATE_FFW_STARTED
WRSIPOD_PLAY_STATE_REW_STARTED = _wrs_ipod_2.WRSIPOD_PLAY_STATE_REW_STARTED
WRSIPOD_PLAY_STATE_FFWREW_STOPPED = _wrs_ipod_2.WRSIPOD_PLAY_STATE_FFWREW_STOPPED
WRSIPOD_PLAY_STATE_PLAYING = _wrs_ipod_2.WRSIPOD_PLAY_STATE_PLAYING
WRSIPOD_PLAY_STATE_PAUSED = _wrs_ipod_2.WRSIPOD_PLAY_STATE_PAUSED
WRSIPOD_SHUFFLE_OFF = _wrs_ipod_2.WRSIPOD_SHUFFLE_OFF
WRSIPOD_SHUFFLE_TRACKS = _wrs_ipod_2.WRSIPOD_SHUFFLE_TRACKS
WRSIPOD_SHUFFLE_ALBUMS = _wrs_ipod_2.WRSIPOD_SHUFFLE_ALBUMS
WRSIPOD_REPEAT_OFF = _wrs_ipod_2.WRSIPOD_REPEAT_OFF
WRSIPOD_REPEAT_ONE_TRACK = _wrs_ipod_2.WRSIPOD_REPEAT_ONE_TRACK
WRSIPOD_REPEAT_ALL_TRACKS = _wrs_ipod_2.WRSIPOD_REPEAT_ALL_TRACKS
WRSIPOD_HIERARCHY_AUDIO = _wrs_ipod_2.WRSIPOD_HIERARCHY_AUDIO
WRSIPOD_HIERARCHY_VIDEO = _wrs_ipod_2.WRSIPOD_HIERARCHY_VIDEO
WRSIPOD_PREFKEY_VIDEOOUT = _wrs_ipod_2.WRSIPOD_PREFKEY_VIDEOOUT
WRSIPOD_PREFKEY_SCREEN = _wrs_ipod_2.WRSIPOD_PREFKEY_SCREEN
WRSIPOD_PREFKEY_VIDEOFORMAT = _wrs_ipod_2.WRSIPOD_PREFKEY_VIDEOFORMAT
WRSIPOD_PREFKEY_LINEOUT = _wrs_ipod_2.WRSIPOD_PREFKEY_LINEOUT
WRSIPOD_PREFKEY_VIDEOCONNECTION = _wrs_ipod_2.WRSIPOD_PREFKEY_VIDEOCONNECTION
WRSIPOD_PREFKEY_CLOSEDCAPTION = _wrs_ipod_2.WRSIPOD_PREFKEY_CLOSEDCAPTION
WRSIPOD_PREFKEY_VIDEORATIO = _wrs_ipod_2.WRSIPOD_PREFKEY_VIDEORATIO
WRSIPOD_PREFKEY_SUBTITLE = _wrs_ipod_2.WRSIPOD_PREFKEY_SUBTITLE
WRSIPOD_PREFKEY_ALTERNATEAUDIO = _wrs_ipod_2.WRSIPOD_PREFKEY_ALTERNATEAUDIO
WRSIPOD_PREFVAL_VIDEOOUT_OFF = _wrs_ipod_2.WRSIPOD_PREFVAL_VIDEOOUT_OFF
WRSIPOD_PREFVAL_VIDEOOUT_ON = _wrs_ipod_2.WRSIPOD_PREFVAL_VIDEOOUT_ON
WRSIPOD_PREFVAL_SCREEN_FILL_ENTIRE = _wrs_ipod_2.WRSIPOD_PREFVAL_SCREEN_FILL_ENTIRE
WRSIPOD_PREFVAL_SCREEN_FIT_TO_EDGE = _wrs_ipod_2.WRSIPOD_PREFVAL_SCREEN_FIT_TO_EDGE
WRSIPOD_PREFVAL_VIDEOFORMAT_NTSC = _wrs_ipod_2.WRSIPOD_PREFVAL_VIDEOFORMAT_NTSC
WRSIPOD_PREFVAL_VIDEOFORMAT_PAL = _wrs_ipod_2.WRSIPOD_PREFVAL_VIDEOFORMAT_PAL
WRSIPOD_PREFVAL_LINEOUT_NOT_USED = _wrs_ipod_2.WRSIPOD_PREFVAL_LINEOUT_NOT_USED
WRSIPOD_PREFVAL_LINEOUT_USED = _wrs_ipod_2.WRSIPOD_PREFVAL_LINEOUT_USED
WRSIPOD_PREFVAL_VIDEOCONNECTION_NONE = _wrs_ipod_2.WRSIPOD_PREFVAL_VIDEOCONNECTION_NONE
WRSIPOD_PREFVAL_VIDEOCONNECTION_COMPOSITE = _wrs_ipod_2.WRSIPOD_PREFVAL_VIDEOCONNECTION_COMPOSITE
WRSIPOD_PREFVAL_VIDEOCONNECTION_SVIDEO = _wrs_ipod_2.WRSIPOD_PREFVAL_VIDEOCONNECTION_SVIDEO
WRSIPOD_PREFVAL_VIDEOCONNECTION_COMPONENT = _wrs_ipod_2.WRSIPOD_PREFVAL_VIDEOCONNECTION_COMPONENT
WRSIPOD_PREFVAL_CLOSEDCAPTION_OFF = _wrs_ipod_2.WRSIPOD_PREFVAL_CLOSEDCAPTION_OFF
WRSIPOD_PREFVAL_CLOSEDCAPTION_ON = _wrs_ipod_2.WRSIPOD_PREFVAL_CLOSEDCAPTION_ON
WRSIPOD_PREFVAL_VIDEORATIO_4_3 = _wrs_ipod_2.WRSIPOD_PREFVAL_VIDEORATIO_4_3
WRSIPOD_PREFVAL_VIDEORATIO_16_9 = _wrs_ipod_2.WRSIPOD_PREFVAL_VIDEORATIO_16_9
WRSIPOD_PREFVAL_SUBTITLE_OFF = _wrs_ipod_2.WRSIPOD_PREFVAL_SUBTITLE_OFF
WRSIPOD_PREFVAL_SUBTITLE_ON = _wrs_ipod_2.WRSIPOD_PREFVAL_SUBTITLE_ON
WRSIPOD_PREFVAL_ALTERNATEAUDIO_OFF = _wrs_ipod_2.WRSIPOD_PREFVAL_ALTERNATEAUDIO_OFF
WRSIPOD_PREFVAL_ALTERNATEAUDIO_ON = _wrs_ipod_2.WRSIPOD_PREFVAL_ALTERNATEAUDIO_ON
WRSIPOD_PREFVAL_UNKNOWN = _wrs_ipod_2.WRSIPOD_PREFVAL_UNKNOWN
WRSIPOD_CATEGORY_TOP = _wrs_ipod_2.WRSIPOD_CATEGORY_TOP
WRSIPOD_CATEGORY_PLAYLIST = _wrs_ipod_2.WRSIPOD_CATEGORY_PLAYLIST
WRSIPOD_CATEGORY_ARTIST = _wrs_ipod_2.WRSIPOD_CATEGORY_ARTIST
WRSIPOD_CATEGORY_ALBUM = _wrs_ipod_2.WRSIPOD_CATEGORY_ALBUM
WRSIPOD_CATEGORY_GENRE = _wrs_ipod_2.WRSIPOD_CATEGORY_GENRE
WRSIPOD_CATEGORY_TRACK = _wrs_ipod_2.WRSIPOD_CATEGORY_TRACK
WRSIPOD_CATEGORY_COMPOSER = _wrs_ipod_2.WRSIPOD_CATEGORY_COMPOSER
WRSIPOD_CATEGORY_AUDIOBOOK = _wrs_ipod_2.WRSIPOD_CATEGORY_AUDIOBOOK
WRSIPOD_CATEGORY_PODCAST = _wrs_ipod_2.WRSIPOD_CATEGORY_PODCAST
WRSIPOD_CATEGORY_NESTED_PLAYLIST = _wrs_ipod_2.WRSIPOD_CATEGORY_NESTED_PLAYLIST
WRSIPOD_CATEGORY_GENIUS_MIXES = _wrs_ipod_2.WRSIPOD_CATEGORY_GENIUS_MIXES
WRSIPOD_CATEGORY_ITUNES_U = _wrs_ipod_2.WRSIPOD_CATEGORY_ITUNES_U

def wrs_ipod_connect(*args):
  return _wrs_ipod_2.wrs_ipod_connect(*args)
wrs_ipod_connect = _wrs_ipod_2.wrs_ipod_connect

def wrs_ipod_fd(*args):
  return _wrs_ipod_2.wrs_ipod_fd(*args)
wrs_ipod_fd = _wrs_ipod_2.wrs_ipod_fd

def wrs_ipod_pid(*args):
  return _wrs_ipod_2.wrs_ipod_pid(*args)
wrs_ipod_pid = _wrs_ipod_2.wrs_ipod_pid

def wrs_ipod_ping(*args):
  return _wrs_ipod_2.wrs_ipod_ping(*args)
wrs_ipod_ping = _wrs_ipod_2.wrs_ipod_ping

def wrs_ipod_close(*args):
  return _wrs_ipod_2.wrs_ipod_close(*args)
wrs_ipod_close = _wrs_ipod_2.wrs_ipod_close

def wrs_ipod_is_ready(*args):
  return _wrs_ipod_2.wrs_ipod_is_ready(*args)
wrs_ipod_is_ready = _wrs_ipod_2.wrs_ipod_is_ready

def wrs_ipod_is_remote(*args):
  return _wrs_ipod_2.wrs_ipod_is_remote(*args)
wrs_ipod_is_remote = _wrs_ipod_2.wrs_ipod_is_remote

def wrs_ipod_is_session_opened(*args):
  return _wrs_ipod_2.wrs_ipod_is_session_opened(*args)
wrs_ipod_is_session_opened = _wrs_ipod_2.wrs_ipod_is_session_opened

def wrs_ipod_read(*args):
  return _wrs_ipod_2.wrs_ipod_read(*args)
wrs_ipod_read = _wrs_ipod_2.wrs_ipod_read

def wrs_ipod_device_count(*args):
  return _wrs_ipod_2.wrs_ipod_device_count(*args)
wrs_ipod_device_count = _wrs_ipod_2.wrs_ipod_device_count

def wrs_ipod_device_name(*args):
  return _wrs_ipod_2.wrs_ipod_device_name(*args)
wrs_ipod_device_name = _wrs_ipod_2.wrs_ipod_device_name

def wrs_ipod_device_serial(*args):
  return _wrs_ipod_2.wrs_ipod_device_serial(*args)
wrs_ipod_device_serial = _wrs_ipod_2.wrs_ipod_device_serial

def wrs_ipod_device_type(*args):
  return _wrs_ipod_2.wrs_ipod_device_type(*args)
wrs_ipod_device_type = _wrs_ipod_2.wrs_ipod_device_type

def wrs_ipod_device_authenticated(*args):
  return _wrs_ipod_2.wrs_ipod_device_authenticated(*args)
wrs_ipod_device_authenticated = _wrs_ipod_2.wrs_ipod_device_authenticated

def wrs_ipod_device_used(*args):
  return _wrs_ipod_2.wrs_ipod_device_used(*args)
wrs_ipod_device_used = _wrs_ipod_2.wrs_ipod_device_used

def wrs_ipod_device_is_extended(*args):
  return _wrs_ipod_2.wrs_ipod_device_is_extended(*args)
wrs_ipod_device_is_extended = _wrs_ipod_2.wrs_ipod_device_is_extended

def wrs_ipod_device_ready(*args):
  return _wrs_ipod_2.wrs_ipod_device_ready(*args)
wrs_ipod_device_ready = _wrs_ipod_2.wrs_ipod_device_ready

def wrs_ipod_device_support_itunes_db(*args):
  return _wrs_ipod_2.wrs_ipod_device_support_itunes_db(*args)
wrs_ipod_device_support_itunes_db = _wrs_ipod_2.wrs_ipod_device_support_itunes_db

def wrs_ipod_device_audio_count(*args):
  return _wrs_ipod_2.wrs_ipod_device_audio_count(*args)
wrs_ipod_device_audio_count = _wrs_ipod_2.wrs_ipod_device_audio_count

def wrs_ipod_device_index(*args):
  return _wrs_ipod_2.wrs_ipod_device_index(*args)
wrs_ipod_device_index = _wrs_ipod_2.wrs_ipod_device_index

def wrs_ipod_set_event_cb(*args):
  return _wrs_ipod_2.wrs_ipod_set_event_cb(*args)
wrs_ipod_set_event_cb = _wrs_ipod_2.wrs_ipod_set_event_cb

def wrs_ipod_set_reply_cb(*args):
  return _wrs_ipod_2.wrs_ipod_set_reply_cb(*args)
wrs_ipod_set_reply_cb = _wrs_ipod_2.wrs_ipod_set_reply_cb

def wrs_ipod_set_ping_cb(*args):
  return _wrs_ipod_2.wrs_ipod_set_ping_cb(*args)
wrs_ipod_set_ping_cb = _wrs_ipod_2.wrs_ipod_set_ping_cb

def wrs_ipod_event_type(*args):
  return _wrs_ipod_2.wrs_ipod_event_type(*args)
wrs_ipod_event_type = _wrs_ipod_2.wrs_ipod_event_type

def wrs_ipod_event_connected_serial(*args):
  return _wrs_ipod_2.wrs_ipod_event_connected_serial(*args)
wrs_ipod_event_connected_serial = _wrs_ipod_2.wrs_ipod_event_connected_serial

def wrs_ipod_event_disconnected_serial(*args):
  return _wrs_ipod_2.wrs_ipod_event_disconnected_serial(*args)
wrs_ipod_event_disconnected_serial = _wrs_ipod_2.wrs_ipod_event_disconnected_serial

def wrs_ipod_event_device_serial(*args):
  return _wrs_ipod_2.wrs_ipod_event_device_serial(*args)
wrs_ipod_event_device_serial = _wrs_ipod_2.wrs_ipod_event_device_serial

def wrs_ipod_event_authenticated(*args):
  return _wrs_ipod_2.wrs_ipod_event_authenticated(*args)
wrs_ipod_event_authenticated = _wrs_ipod_2.wrs_ipod_event_authenticated

def wrs_ipod_event_mode_changed(*args):
  return _wrs_ipod_2.wrs_ipod_event_mode_changed(*args)
wrs_ipod_event_mode_changed = _wrs_ipod_2.wrs_ipod_event_mode_changed

def wrs_ipod_current_session(*args):
  return _wrs_ipod_2.wrs_ipod_current_session(*args)
wrs_ipod_current_session = _wrs_ipod_2.wrs_ipod_current_session

def wrs_ipod_set_current_session(*args):
  return _wrs_ipod_2.wrs_ipod_set_current_session(*args)
wrs_ipod_set_current_session = _wrs_ipod_2.wrs_ipod_set_current_session

def wrs_ipod_open_session(*args):
  return _wrs_ipod_2.wrs_ipod_open_session(*args)
wrs_ipod_open_session = _wrs_ipod_2.wrs_ipod_open_session

def wrs_ipod_open_session_sync(*args):
  return _wrs_ipod_2.wrs_ipod_open_session_sync(*args)
wrs_ipod_open_session_sync = _wrs_ipod_2.wrs_ipod_open_session_sync

def wrs_ipod_close_session(*args):
  return _wrs_ipod_2.wrs_ipod_close_session(*args)
wrs_ipod_close_session = _wrs_ipod_2.wrs_ipod_close_session

def wrs_ipod_play(*args):
  return _wrs_ipod_2.wrs_ipod_play(*args)
wrs_ipod_play = _wrs_ipod_2.wrs_ipod_play

def wrs_ipod_play_sync(*args):
  return _wrs_ipod_2.wrs_ipod_play_sync(*args)
wrs_ipod_play_sync = _wrs_ipod_2.wrs_ipod_play_sync

def wrs_ipod_stop(*args):
  return _wrs_ipod_2.wrs_ipod_stop(*args)
wrs_ipod_stop = _wrs_ipod_2.wrs_ipod_stop

def wrs_ipod_stop_sync(*args):
  return _wrs_ipod_2.wrs_ipod_stop_sync(*args)
wrs_ipod_stop_sync = _wrs_ipod_2.wrs_ipod_stop_sync

def wrs_ipod_pause(*args):
  return _wrs_ipod_2.wrs_ipod_pause(*args)
wrs_ipod_pause = _wrs_ipod_2.wrs_ipod_pause

def wrs_ipod_pause_sync(*args):
  return _wrs_ipod_2.wrs_ipod_pause_sync(*args)
wrs_ipod_pause_sync = _wrs_ipod_2.wrs_ipod_pause_sync

def wrs_ipod_next_track(*args):
  return _wrs_ipod_2.wrs_ipod_next_track(*args)
wrs_ipod_next_track = _wrs_ipod_2.wrs_ipod_next_track

def wrs_ipod_next_track_sync(*args):
  return _wrs_ipod_2.wrs_ipod_next_track_sync(*args)
wrs_ipod_next_track_sync = _wrs_ipod_2.wrs_ipod_next_track_sync

def wrs_ipod_prev_track(*args):
  return _wrs_ipod_2.wrs_ipod_prev_track(*args)
wrs_ipod_prev_track = _wrs_ipod_2.wrs_ipod_prev_track

def wrs_ipod_prev_track_sync(*args):
  return _wrs_ipod_2.wrs_ipod_prev_track_sync(*args)
wrs_ipod_prev_track_sync = _wrs_ipod_2.wrs_ipod_prev_track_sync

def wrs_ipod_start_ffw(*args):
  return _wrs_ipod_2.wrs_ipod_start_ffw(*args)
wrs_ipod_start_ffw = _wrs_ipod_2.wrs_ipod_start_ffw

def wrs_ipod_start_ffw_sync(*args):
  return _wrs_ipod_2.wrs_ipod_start_ffw_sync(*args)
wrs_ipod_start_ffw_sync = _wrs_ipod_2.wrs_ipod_start_ffw_sync

def wrs_ipod_start_rew(*args):
  return _wrs_ipod_2.wrs_ipod_start_rew(*args)
wrs_ipod_start_rew = _wrs_ipod_2.wrs_ipod_start_rew

def wrs_ipod_start_rew_sync(*args):
  return _wrs_ipod_2.wrs_ipod_start_rew_sync(*args)
wrs_ipod_start_rew_sync = _wrs_ipod_2.wrs_ipod_start_rew_sync

def wrs_ipod_set_position(*args):
  return _wrs_ipod_2.wrs_ipod_set_position(*args)
wrs_ipod_set_position = _wrs_ipod_2.wrs_ipod_set_position

def wrs_ipod_set_position_sync(*args):
  return _wrs_ipod_2.wrs_ipod_set_position_sync(*args)
wrs_ipod_set_position_sync = _wrs_ipod_2.wrs_ipod_set_position_sync

def wrs_ipod_stop_ffwrew(*args):
  return _wrs_ipod_2.wrs_ipod_stop_ffwrew(*args)
wrs_ipod_stop_ffwrew = _wrs_ipod_2.wrs_ipod_stop_ffwrew

def wrs_ipod_stop_ffwrew_sync(*args):
  return _wrs_ipod_2.wrs_ipod_stop_ffwrew_sync(*args)
wrs_ipod_stop_ffwrew_sync = _wrs_ipod_2.wrs_ipod_stop_ffwrew_sync

def wrs_ipod_get_play_state(*args):
  return _wrs_ipod_2.wrs_ipod_get_play_state(*args)
wrs_ipod_get_play_state = _wrs_ipod_2.wrs_ipod_get_play_state

def wrs_ipod_get_play_state_sync(*args):
  return _wrs_ipod_2.wrs_ipod_get_play_state_sync(*args)
wrs_ipod_get_play_state_sync = _wrs_ipod_2.wrs_ipod_get_play_state_sync

def wrs_ipod_get_current_track_index(*args):
  return _wrs_ipod_2.wrs_ipod_get_current_track_index(*args)
wrs_ipod_get_current_track_index = _wrs_ipod_2.wrs_ipod_get_current_track_index

def wrs_ipod_get_current_track_index_sync(*args):
  return _wrs_ipod_2.wrs_ipod_get_current_track_index_sync(*args)
wrs_ipod_get_current_track_index_sync = _wrs_ipod_2.wrs_ipod_get_current_track_index_sync

def wrs_ipod_set_shuffle(*args):
  return _wrs_ipod_2.wrs_ipod_set_shuffle(*args)
wrs_ipod_set_shuffle = _wrs_ipod_2.wrs_ipod_set_shuffle

def wrs_ipod_set_shuffle_sync(*args):
  return _wrs_ipod_2.wrs_ipod_set_shuffle_sync(*args)
wrs_ipod_set_shuffle_sync = _wrs_ipod_2.wrs_ipod_set_shuffle_sync

def wrs_ipod_set_repeat(*args):
  return _wrs_ipod_2.wrs_ipod_set_repeat(*args)
wrs_ipod_set_repeat = _wrs_ipod_2.wrs_ipod_set_repeat

def wrs_ipod_set_repeat_sync(*args):
  return _wrs_ipod_2.wrs_ipod_set_repeat_sync(*args)
wrs_ipod_set_repeat_sync = _wrs_ipod_2.wrs_ipod_set_repeat_sync

def wrs_ipod_get_shuffle(*args):
  return _wrs_ipod_2.wrs_ipod_get_shuffle(*args)
wrs_ipod_get_shuffle = _wrs_ipod_2.wrs_ipod_get_shuffle

def wrs_ipod_get_shuffle_sync(*args):
  return _wrs_ipod_2.wrs_ipod_get_shuffle_sync(*args)
wrs_ipod_get_shuffle_sync = _wrs_ipod_2.wrs_ipod_get_shuffle_sync

def wrs_ipod_get_repeat(*args):
  return _wrs_ipod_2.wrs_ipod_get_repeat(*args)
wrs_ipod_get_repeat = _wrs_ipod_2.wrs_ipod_get_repeat

def wrs_ipod_get_repeat_sync(*args):
  return _wrs_ipod_2.wrs_ipod_get_repeat_sync(*args)
wrs_ipod_get_repeat_sync = _wrs_ipod_2.wrs_ipod_get_repeat_sync

def wrs_ipod_write_tag(*args):
  return _wrs_ipod_2.wrs_ipod_write_tag(*args)
wrs_ipod_write_tag = _wrs_ipod_2.wrs_ipod_write_tag

def wrs_ipod_write_tag_sync(*args):
  return _wrs_ipod_2.wrs_ipod_write_tag_sync(*args)
wrs_ipod_write_tag_sync = _wrs_ipod_2.wrs_ipod_write_tag_sync

def wrs_ipod_set_preference(*args):
  return _wrs_ipod_2.wrs_ipod_set_preference(*args)
wrs_ipod_set_preference = _wrs_ipod_2.wrs_ipod_set_preference

def wrs_ipod_set_preference_sync(*args):
  return _wrs_ipod_2.wrs_ipod_set_preference_sync(*args)
wrs_ipod_set_preference_sync = _wrs_ipod_2.wrs_ipod_set_preference_sync

def wrs_ipod_get_preference(*args):
  return _wrs_ipod_2.wrs_ipod_get_preference(*args)
wrs_ipod_get_preference = _wrs_ipod_2.wrs_ipod_get_preference

def wrs_ipod_get_preference_sync(*args):
  return _wrs_ipod_2.wrs_ipod_get_preference_sync(*args)
wrs_ipod_get_preference_sync = _wrs_ipod_2.wrs_ipod_get_preference_sync

def wrs_ipod_current_track_info(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_info(*args)
wrs_ipod_current_track_info = _wrs_ipod_2.wrs_ipod_current_track_info

def wrs_ipod_current_track_info_sync(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_info_sync(*args)
wrs_ipod_current_track_info_sync = _wrs_ipod_2.wrs_ipod_current_track_info_sync

def wrs_ipod_get_sample_rate(*args):
  return _wrs_ipod_2.wrs_ipod_get_sample_rate(*args)
wrs_ipod_get_sample_rate = _wrs_ipod_2.wrs_ipod_get_sample_rate

def wrs_ipod_current_track_title(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_title(*args)
wrs_ipod_current_track_title = _wrs_ipod_2.wrs_ipod_current_track_title

def wrs_ipod_current_track_uid(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_uid(*args)
wrs_ipod_current_track_uid = _wrs_ipod_2.wrs_ipod_current_track_uid

def wrs_ipod_current_track_artist(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_artist(*args)
wrs_ipod_current_track_artist = _wrs_ipod_2.wrs_ipod_current_track_artist

def wrs_ipod_current_track_album(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_album(*args)
wrs_ipod_current_track_album = _wrs_ipod_2.wrs_ipod_current_track_album

def wrs_ipod_current_track_chapter(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_chapter(*args)
wrs_ipod_current_track_chapter = _wrs_ipod_2.wrs_ipod_current_track_chapter

def wrs_ipod_current_number_of_tracks(*args):
  return _wrs_ipod_2.wrs_ipod_current_number_of_tracks(*args)
wrs_ipod_current_number_of_tracks = _wrs_ipod_2.wrs_ipod_current_number_of_tracks

def wrs_ipod_current_track_index(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_index(*args)
wrs_ipod_current_track_index = _wrs_ipod_2.wrs_ipod_current_track_index

def wrs_ipod_current_chapter_index(*args):
  return _wrs_ipod_2.wrs_ipod_current_chapter_index(*args)
wrs_ipod_current_chapter_index = _wrs_ipod_2.wrs_ipod_current_chapter_index

def wrs_ipod_current_chapter_count(*args):
  return _wrs_ipod_2.wrs_ipod_current_chapter_count(*args)
wrs_ipod_current_chapter_count = _wrs_ipod_2.wrs_ipod_current_chapter_count

def wrs_ipod_current_track_length(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_length(*args)
wrs_ipod_current_track_length = _wrs_ipod_2.wrs_ipod_current_track_length

def wrs_ipod_current_track_position(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_position(*args)
wrs_ipod_current_track_position = _wrs_ipod_2.wrs_ipod_current_track_position

def wrs_ipod_current_track_timestamp(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_timestamp(*args)
wrs_ipod_current_track_timestamp = _wrs_ipod_2.wrs_ipod_current_track_timestamp

def wrs_ipod_current_track_has_artwork(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_has_artwork(*args)
wrs_ipod_current_track_has_artwork = _wrs_ipod_2.wrs_ipod_current_track_has_artwork

def wrs_ipod_current_track_has_chapters(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_has_chapters(*args)
wrs_ipod_current_track_has_chapters = _wrs_ipod_2.wrs_ipod_current_track_has_chapters

def wrs_ipod_current_track_state(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_state(*args)
wrs_ipod_current_track_state = _wrs_ipod_2.wrs_ipod_current_track_state

def wrs_ipod_current_sample_rate(*args):
  return _wrs_ipod_2.wrs_ipod_current_sample_rate(*args)
wrs_ipod_current_sample_rate = _wrs_ipod_2.wrs_ipod_current_sample_rate

def wrs_ipod_current_track_is_audiobook(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_is_audiobook(*args)
wrs_ipod_current_track_is_audiobook = _wrs_ipod_2.wrs_ipod_current_track_is_audiobook

def wrs_ipod_current_track_is_podcast(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_is_podcast(*args)
wrs_ipod_current_track_is_podcast = _wrs_ipod_2.wrs_ipod_current_track_is_podcast

def wrs_ipod_current_shuffle_state(*args):
  return _wrs_ipod_2.wrs_ipod_current_shuffle_state(*args)
wrs_ipod_current_shuffle_state = _wrs_ipod_2.wrs_ipod_current_shuffle_state

def wrs_ipod_current_repeat_state(*args):
  return _wrs_ipod_2.wrs_ipod_current_repeat_state(*args)
wrs_ipod_current_repeat_state = _wrs_ipod_2.wrs_ipod_current_repeat_state

def wrs_ipod_current_track_artwork(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_artwork(*args)
wrs_ipod_current_track_artwork = _wrs_ipod_2.wrs_ipod_current_track_artwork

def wrs_ipod_current_track_artwork_sync(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_artwork_sync(*args)
wrs_ipod_current_track_artwork_sync = _wrs_ipod_2.wrs_ipod_current_track_artwork_sync

def wrs_ipod_current_track_artwork_length(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_artwork_length(*args)
wrs_ipod_current_track_artwork_length = _wrs_ipod_2.wrs_ipod_current_track_artwork_length

def wrs_ipod_current_track_artwork_data(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_artwork_data(*args)
wrs_ipod_current_track_artwork_data = _wrs_ipod_2.wrs_ipod_current_track_artwork_data

def wrs_ipod_current_track_artwork_width(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_artwork_width(*args)
wrs_ipod_current_track_artwork_width = _wrs_ipod_2.wrs_ipod_current_track_artwork_width

def wrs_ipod_current_track_artwork_height(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_artwork_height(*args)
wrs_ipod_current_track_artwork_height = _wrs_ipod_2.wrs_ipod_current_track_artwork_height

def wrs_ipod_current_track_artwork_rowstride(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_artwork_rowstride(*args)
wrs_ipod_current_track_artwork_rowstride = _wrs_ipod_2.wrs_ipod_current_track_artwork_rowstride

def wrs_ipod_set_hierarchy(*args):
  return _wrs_ipod_2.wrs_ipod_set_hierarchy(*args)
wrs_ipod_set_hierarchy = _wrs_ipod_2.wrs_ipod_set_hierarchy

def wrs_ipod_set_hierarchy_sync(*args):
  return _wrs_ipod_2.wrs_ipod_set_hierarchy_sync(*args)
wrs_ipod_set_hierarchy_sync = _wrs_ipod_2.wrs_ipod_set_hierarchy_sync

def wrs_ipod_set_category(*args):
  return _wrs_ipod_2.wrs_ipod_set_category(*args)
wrs_ipod_set_category = _wrs_ipod_2.wrs_ipod_set_category

def wrs_ipod_set_category_sync(*args):
  return _wrs_ipod_2.wrs_ipod_set_category_sync(*args)
wrs_ipod_set_category_sync = _wrs_ipod_2.wrs_ipod_set_category_sync

def wrs_ipod_get_category(*args):
  return _wrs_ipod_2.wrs_ipod_get_category(*args)
wrs_ipod_get_category = _wrs_ipod_2.wrs_ipod_get_category

def wrs_ipod_select_db(*args):
  return _wrs_ipod_2.wrs_ipod_select_db(*args)
wrs_ipod_select_db = _wrs_ipod_2.wrs_ipod_select_db

def wrs_ipod_select_db_sync(*args):
  return _wrs_ipod_2.wrs_ipod_select_db_sync(*args)
wrs_ipod_select_db_sync = _wrs_ipod_2.wrs_ipod_select_db_sync

def wrs_ipod_get_records(*args):
  return _wrs_ipod_2.wrs_ipod_get_records(*args)
wrs_ipod_get_records = _wrs_ipod_2.wrs_ipod_get_records

def wrs_ipod_get_records_sync(*args):
  return _wrs_ipod_2.wrs_ipod_get_records_sync(*args)
wrs_ipod_get_records_sync = _wrs_ipod_2.wrs_ipod_get_records_sync

def wrs_ipod_record_count(*args):
  return _wrs_ipod_2.wrs_ipod_record_count(*args)
wrs_ipod_record_count = _wrs_ipod_2.wrs_ipod_record_count

def wrs_ipod_record(*args):
  return _wrs_ipod_2.wrs_ipod_record(*args)
wrs_ipod_record = _wrs_ipod_2.wrs_ipod_record

def wrs_ipod_records(*args):
  return _wrs_ipod_2.wrs_ipod_records(*args)
wrs_ipod_records = _wrs_ipod_2.wrs_ipod_records

def wrs_ipod_reauthentication(*args):
  return _wrs_ipod_2.wrs_ipod_reauthentication(*args)
wrs_ipod_reauthentication = _wrs_ipod_2.wrs_ipod_reauthentication

def wrs_ipod_reauthentication_sync(*args):
  return _wrs_ipod_2.wrs_ipod_reauthentication_sync(*args)
wrs_ipod_reauthentication_sync = _wrs_ipod_2.wrs_ipod_reauthentication_sync

def wrs_ipod_enter_videooutmode(*args):
  return _wrs_ipod_2.wrs_ipod_enter_videooutmode(*args)
wrs_ipod_enter_videooutmode = _wrs_ipod_2.wrs_ipod_enter_videooutmode

def wrs_ipod_enter_videooutmode_sync(*args):
  return _wrs_ipod_2.wrs_ipod_enter_videooutmode_sync(*args)
wrs_ipod_enter_videooutmode_sync = _wrs_ipod_2.wrs_ipod_enter_videooutmode_sync

def wrs_ipod_exit_videooutmode(*args):
  return _wrs_ipod_2.wrs_ipod_exit_videooutmode(*args)
wrs_ipod_exit_videooutmode = _wrs_ipod_2.wrs_ipod_exit_videooutmode

def wrs_ipod_get_videooutoptions(*args):
  return _wrs_ipod_2.wrs_ipod_get_videooutoptions(*args)
wrs_ipod_get_videooutoptions = _wrs_ipod_2.wrs_ipod_get_videooutoptions

def wrs_ipod_get_videooutoptions_sync(*args):
  return _wrs_ipod_2.wrs_ipod_get_videooutoptions_sync(*args)
wrs_ipod_get_videooutoptions_sync = _wrs_ipod_2.wrs_ipod_get_videooutoptions_sync

def wrs_ipod_set_videooutoptions(*args):
  return _wrs_ipod_2.wrs_ipod_set_videooutoptions(*args)
wrs_ipod_set_videooutoptions = _wrs_ipod_2.wrs_ipod_set_videooutoptions

def wrs_ipod_set_videooutoptions_sync(*args):
  return _wrs_ipod_2.wrs_ipod_set_videooutoptions_sync(*args)
wrs_ipod_set_videooutoptions_sync = _wrs_ipod_2.wrs_ipod_set_videooutoptions_sync

def wrs_ipod_set_statechange(*args):
  return _wrs_ipod_2.wrs_ipod_set_statechange(*args)
wrs_ipod_set_statechange = _wrs_ipod_2.wrs_ipod_set_statechange

def wrs_ipod_set_statechange_sync(*args):
  return _wrs_ipod_2.wrs_ipod_set_statechange_sync(*args)
wrs_ipod_set_statechange_sync = _wrs_ipod_2.wrs_ipod_set_statechange_sync

def wrs_ipod_get_mode(*args):
  return _wrs_ipod_2.wrs_ipod_get_mode(*args)
wrs_ipod_get_mode = _wrs_ipod_2.wrs_ipod_get_mode

def wrs_ipod_navigate_videoout(*args):
  return _wrs_ipod_2.wrs_ipod_navigate_videoout(*args)
wrs_ipod_navigate_videoout = _wrs_ipod_2.wrs_ipod_navigate_videoout

def wrs_ipod_navigate_videoout_sync(*args):
  return _wrs_ipod_2.wrs_ipod_navigate_videoout_sync(*args)
wrs_ipod_navigate_videoout_sync = _wrs_ipod_2.wrs_ipod_navigate_videoout_sync

def wrs_ipod_current_track_timestamp_usec(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_timestamp_usec(*args)
wrs_ipod_current_track_timestamp_usec = _wrs_ipod_2.wrs_ipod_current_track_timestamp_usec

def wrs_ipod_get_db_itunes_info(*args):
  return _wrs_ipod_2.wrs_ipod_get_db_itunes_info(*args)
wrs_ipod_get_db_itunes_info = _wrs_ipod_2.wrs_ipod_get_db_itunes_info

def wrs_ipod_get_db_track_info(*args):
  return _wrs_ipod_2.wrs_ipod_get_db_track_info(*args)
wrs_ipod_get_db_track_info = _wrs_ipod_2.wrs_ipod_get_db_track_info

def wrs_ipod_get_db_track_info_sync(*args):
  return _wrs_ipod_2.wrs_ipod_get_db_track_info_sync(*args)
wrs_ipod_get_db_track_info_sync = _wrs_ipod_2.wrs_ipod_get_db_track_info_sync

def wrs_ipod_get_pb_track_info(*args):
  return _wrs_ipod_2.wrs_ipod_get_pb_track_info(*args)
wrs_ipod_get_pb_track_info = _wrs_ipod_2.wrs_ipod_get_pb_track_info

def wrs_ipod_get_pb_track_info_sync(*args):
  return _wrs_ipod_2.wrs_ipod_get_pb_track_info_sync(*args)
wrs_ipod_get_pb_track_info_sync = _wrs_ipod_2.wrs_ipod_get_pb_track_info_sync

def wrs_ipod_request_lingo_version(*args):
  return _wrs_ipod_2.wrs_ipod_request_lingo_version(*args)
wrs_ipod_request_lingo_version = _wrs_ipod_2.wrs_ipod_request_lingo_version

def wrs_ipod_get_result_lingo_version(*args):
  return _wrs_ipod_2.wrs_ipod_get_result_lingo_version(*args)
wrs_ipod_get_result_lingo_version = _wrs_ipod_2.wrs_ipod_get_result_lingo_version

def wrs_ipod_request_lingo_version_sync(*args):
  return _wrs_ipod_2.wrs_ipod_request_lingo_version_sync(*args)
wrs_ipod_request_lingo_version_sync = _wrs_ipod_2.wrs_ipod_request_lingo_version_sync

def wrs_ipod_get_result_db_device_uid(*args):
  return _wrs_ipod_2.wrs_ipod_get_result_db_device_uid(*args)
wrs_ipod_get_result_db_device_uid = _wrs_ipod_2.wrs_ipod_get_result_db_device_uid

def wrs_ipod_get_result_db_last_sync_time(*args):
  return _wrs_ipod_2.wrs_ipod_get_result_db_last_sync_time(*args)
wrs_ipod_get_result_db_last_sync_time = _wrs_ipod_2.wrs_ipod_get_result_db_last_sync_time

def wrs_ipod_get_result_db_itunes_info_count(*args):
  return _wrs_ipod_2.wrs_ipod_get_result_db_itunes_info_count(*args)
wrs_ipod_get_result_db_itunes_info_count = _wrs_ipod_2.wrs_ipod_get_result_db_itunes_info_count

def wrs_ipod_get_result_db_track_info(*args):
  return _wrs_ipod_2.wrs_ipod_get_result_db_track_info(*args)
wrs_ipod_get_result_db_track_info = _wrs_ipod_2.wrs_ipod_get_result_db_track_info

def wrs_ipod_get_result_pb_track_info(*args):
  return _wrs_ipod_2.wrs_ipod_get_result_pb_track_info(*args)
wrs_ipod_get_result_pb_track_info = _wrs_ipod_2.wrs_ipod_get_result_pb_track_info

def wrs_ipod_prepare_uid_list(*args):
  return _wrs_ipod_2.wrs_ipod_prepare_uid_list(*args)
wrs_ipod_prepare_uid_list = _wrs_ipod_2.wrs_ipod_prepare_uid_list

def wrs_ipod_prepare_uid_list_sync(*args):
  return _wrs_ipod_2.wrs_ipod_prepare_uid_list_sync(*args)
wrs_ipod_prepare_uid_list_sync = _wrs_ipod_2.wrs_ipod_prepare_uid_list_sync

def wrs_ipod_play_uid_list(*args):
  return _wrs_ipod_2.wrs_ipod_play_uid_list(*args)
wrs_ipod_play_uid_list = _wrs_ipod_2.wrs_ipod_play_uid_list

def wrs_ipod_play_uid_list_sync(*args):
  return _wrs_ipod_2.wrs_ipod_play_uid_list_sync(*args)
wrs_ipod_play_uid_list_sync = _wrs_ipod_2.wrs_ipod_play_uid_list_sync

def wrs_ipod_set_current_playing_track_chapter(*args):
  return _wrs_ipod_2.wrs_ipod_set_current_playing_track_chapter(*args)
wrs_ipod_set_current_playing_track_chapter = _wrs_ipod_2.wrs_ipod_set_current_playing_track_chapter

def wrs_ipod_set_current_playing_track(*args):
  return _wrs_ipod_2.wrs_ipod_set_current_playing_track(*args)
wrs_ipod_set_current_playing_track = _wrs_ipod_2.wrs_ipod_set_current_playing_track

def wrs_ipod_indexed_track_info(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_info(*args)
wrs_ipod_indexed_track_info = _wrs_ipod_2.wrs_ipod_indexed_track_info

def wrs_ipod_indexed_track_info_sync(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_info_sync(*args)
wrs_ipod_indexed_track_info_sync = _wrs_ipod_2.wrs_ipod_indexed_track_info_sync

def wrs_ipod_get_result_indexed_track_info(*args):
  return _wrs_ipod_2.wrs_ipod_get_result_indexed_track_info(*args)
wrs_ipod_get_result_indexed_track_info = _wrs_ipod_2.wrs_ipod_get_result_indexed_track_info

def wrs_ipod_indexed_track_chapter_info(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_chapter_info(*args)
wrs_ipod_indexed_track_chapter_info = _wrs_ipod_2.wrs_ipod_indexed_track_chapter_info

def wrs_ipod_indexed_track_chapter_info_sync(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_chapter_info_sync(*args)
wrs_ipod_indexed_track_chapter_info_sync = _wrs_ipod_2.wrs_ipod_indexed_track_chapter_info_sync

def wrs_ipod_get_result_indexed_track_chapter_info(*args):
  return _wrs_ipod_2.wrs_ipod_get_result_indexed_track_chapter_info(*args)
wrs_ipod_get_result_indexed_track_chapter_info = _wrs_ipod_2.wrs_ipod_get_result_indexed_track_chapter_info

def wrs_ipod_indexed_track_title(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_title(*args)
wrs_ipod_indexed_track_title = _wrs_ipod_2.wrs_ipod_indexed_track_title

def wrs_ipod_indexed_track_uid(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_uid(*args)
wrs_ipod_indexed_track_uid = _wrs_ipod_2.wrs_ipod_indexed_track_uid

def wrs_ipod_indexed_track_artist(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_artist(*args)
wrs_ipod_indexed_track_artist = _wrs_ipod_2.wrs_ipod_indexed_track_artist

def wrs_ipod_indexed_track_album(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_album(*args)
wrs_ipod_indexed_track_album = _wrs_ipod_2.wrs_ipod_indexed_track_album

def wrs_ipod_indexed_track_composer(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_composer(*args)
wrs_ipod_indexed_track_composer = _wrs_ipod_2.wrs_ipod_indexed_track_composer

def wrs_ipod_indexed_track_genre(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_genre(*args)
wrs_ipod_indexed_track_genre = _wrs_ipod_2.wrs_ipod_indexed_track_genre

def wrs_ipod_indexed_track_is_audiobook(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_is_audiobook(*args)
wrs_ipod_indexed_track_is_audiobook = _wrs_ipod_2.wrs_ipod_indexed_track_is_audiobook

def wrs_ipod_indexed_track_is_podcast(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_is_podcast(*args)
wrs_ipod_indexed_track_is_podcast = _wrs_ipod_2.wrs_ipod_indexed_track_is_podcast

def wrs_ipod_indexed_track_length(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_length(*args)
wrs_ipod_indexed_track_length = _wrs_ipod_2.wrs_ipod_indexed_track_length

def wrs_ipod_indexed_track_chapter_count(*args):
  return _wrs_ipod_2.wrs_ipod_indexed_track_chapter_count(*args)
wrs_ipod_indexed_track_chapter_count = _wrs_ipod_2.wrs_ipod_indexed_track_chapter_count

def wrs_ipod_device_port(*args):
  return _wrs_ipod_2.wrs_ipod_device_port(*args)
wrs_ipod_device_port = _wrs_ipod_2.wrs_ipod_device_port

def wrs_ipod_device_sound_card_id(*args):
  return _wrs_ipod_2.wrs_ipod_device_sound_card_id(*args)
wrs_ipod_device_sound_card_id = _wrs_ipod_2.wrs_ipod_device_sound_card_id

def wrs_ipod_device_product_id(*args):
  return _wrs_ipod_2.wrs_ipod_device_product_id(*args)
wrs_ipod_device_product_id = _wrs_ipod_2.wrs_ipod_device_product_id

def wrs_ipod_set_available_current(*args):
  return _wrs_ipod_2.wrs_ipod_set_available_current(*args)
wrs_ipod_set_available_current = _wrs_ipod_2.wrs_ipod_set_available_current

def wrs_ipod_set_available_current_sync(*args):
  return _wrs_ipod_2.wrs_ipod_set_available_current_sync(*args)
wrs_ipod_set_available_current_sync = _wrs_ipod_2.wrs_ipod_set_available_current_sync

def wrs_ipod_set_bluetooth_state(*args):
  return _wrs_ipod_2.wrs_ipod_set_bluetooth_state(*args)
wrs_ipod_set_bluetooth_state = _wrs_ipod_2.wrs_ipod_set_bluetooth_state

def wrs_ipod_get_artwork_data(*args):
  return _wrs_ipod_2.wrs_ipod_get_artwork_data(*args)
wrs_ipod_get_artwork_data = _wrs_ipod_2.wrs_ipod_get_artwork_data

def wrs_ipod_get_artwork_data_sync(*args):
  return _wrs_ipod_2.wrs_ipod_get_artwork_data_sync(*args)
wrs_ipod_get_artwork_data_sync = _wrs_ipod_2.wrs_ipod_get_artwork_data_sync

def wrs_ipod_set_event_pycb(*args):
  return _wrs_ipod_2.wrs_ipod_set_event_pycb(*args)
wrs_ipod_set_event_pycb = _wrs_ipod_2.wrs_ipod_set_event_pycb

def wrs_ipod_set_reply_pycb(*args):
  return _wrs_ipod_2.wrs_ipod_set_reply_pycb(*args)
wrs_ipod_set_reply_pycb = _wrs_ipod_2.wrs_ipod_set_reply_pycb

def wrs_ipod_current_track_artwork_pydata(*args):
  return _wrs_ipod_2.wrs_ipod_current_track_artwork_pydata(*args)
wrs_ipod_current_track_artwork_pydata = _wrs_ipod_2.wrs_ipod_current_track_artwork_pydata
# This file is compatible with both classic and new-style classes.


