.pragma library
/* XXX THIS FILE WAS GENERATED BY USING config-default.js AND
config-YOURTARGETDEVICE.js IN CONFIGURATION TIME */

// DEFAULT CONFIG VARIABLES
var displayWidth = 0;
var displayHeight = 0;
var statusBarHeight = 0;
var useMultiWindowFeature = false;
var useMultiWaylandDisplayFeature = false;
var densityAdjust = 1.0;

// XXX OVERWRITE DEFAULT CONFIGs FROM HERE
