# -*- coding: utf-8 -*-
from twisted.internet.protocol import DatagramProtocol
from twisted.internet import reactor

from txdbus import client, objects
from txdbus.interface import DBusInterface, Method, Signal

# VehicleInfoEvent (1xx)
VEHICLEINFO = {}
VEHICLEINFO["WMI"] = 101
VEHICLEINFO["VIN"] = 102
VEHICLEINFO["VEHICLETYPE"] = 103
VEHICLEINFO["DOORTYPE_1STROW"] = 104
VEHICLEINFO["DOORTYPE_2NDROW"] = 105
VEHICLEINFO["DOORTYPE_3RDROW"] = 106
VEHICLEINFO["FUELTYPE"] = 107
VEHICLEINFO["TRANSMISSIONGEARTYPE"] = 108
VEHICLEINFO["WHEELINFO_RADIUS"] = 109
VEHICLEINFO["WHEELINFO_TRACK"] = 110

# RunningStatusEvent (2xx)
RUNNINGSTATUS = {}
RUNNINGSTATUS["VEHICLEPOWERMODE"] = 201
RUNNINGSTATUS["SPEEDOMETER"] = 202
RUNNINGSTATUS["ENGINESPEED"] = 203
RUNNINGSTATUS["TRIPMETER_1_MILEAGE"] = 204
RUNNINGSTATUS["TRIPMETER_2_MILEAGE"] = 205
RUNNINGSTATUS["TRIPMETER_1_AVERAGESPEED"] = 206
RUNNINGSTATUS["TRIPMETER_2_AVERAGESPEED"] = 207
RUNNINGSTATUS["TRIPMETER_1_FUELCONSUMPTION"] = 208
RUNNINGSTATUS["TRIPMETER_2_FUELCONSUMPTION"] = 209
RUNNINGSTATUS["TRANSMISSIONGEARSTATUS"] = 210
RUNNINGSTATUS["CRUISECONTROL_STATUS"] = 211
RUNNINGSTATUS["CRUISECONTROL_SPEED"] = 212
RUNNINGSTATUS["WHEELBRAKE"] = 213
RUNNINGSTATUS["LIGHTSSTATUS_HEAD"] = 214
RUNNINGSTATUS["LIGHTSSTATUS_HIGHBEAM"] = 215
RUNNINGSTATUS["LIGHTSSTATUS_TURNLEFT"] = 216
RUNNINGSTATUS["LIGHTSSTATUS_TURNRIGHT"] = 217
RUNNINGSTATUS["LIGHTSSTATUS_BRAKE"] = 218
RUNNINGSTATUS["LIGHTSSTATUS_FOGFRONT"] = 219
RUNNINGSTATUS["LIGHTSSTATUS_FOGREAR"] = 220
RUNNINGSTATUS["LIGHTSSTATUS_HAZARD"] = 221
RUNNINGSTATUS["LIGHTSSTATUS_PARKING"] = 222
RUNNINGSTATUS["INTERIORLIGHTSSTATUS_DRIVER"] = 223
RUNNINGSTATUS["INTERIORLIGHTSSTATUS_PASSENGER"] = 224
RUNNINGSTATUS["INTERIORLIGHTSSTATUS_CENTER"] = 225
RUNNINGSTATUS["AUTOMATICHEADLIGHTS"] = 226
RUNNINGSTATUS["DYNAMICHIGHBEAM"] = 227
RUNNINGSTATUS["HORN"] = 228
RUNNINGSTATUS["CHIME"] = 229
RUNNINGSTATUS["FUEL"] = 230
RUNNINGSTATUS["ESTIMATEDRANGE"] = 231
RUNNINGSTATUS["ENGINEOIL_REMAINING"] = 232
RUNNINGSTATUS["ENGINEOIL_CHANGE"] = 233
RUNNINGSTATUS["ENGINEOIL_TEMP"] = 234
RUNNINGSTATUS["ENGINECOOLANT_LEVEL"] = 235
RUNNINGSTATUS["ENGINECOOLANT_TEMP"] = 236
RUNNINGSTATUS["STEERINGWHEELANGLE"] = 237

# MaintenanceEvent (3xx)
MAINTENANCE = {}
MAINTENANCE["ODOMETER"] = 301
MAINTENANCE["TRANSMISSIONOIL_LIFELEVEL"] = 302
MAINTENANCE["TRANSMISSIONOIL_TEMP"] = 303
MAINTENANCE["BRAKEFLUIDLEVEL"] = 304
MAINTENANCE["WASHERFLUIDLEVEL"] = 305
MAINTENANCE["MALFUNCTIONINDICATORLAMP"] = 306
MAINTENANCE["BATTERY_VOLTAGE"] = 307
MAINTENANCE["BATTERY_CURRENT"] = 308
MAINTENANCE["TIREPRESSURE_FRONTLEFT"] = 309
MAINTENANCE["TIREPRESSURE_FRONTRIGHT"] = 310
MAINTENANCE["TIREPRESSURE_REARLEFT"] = 311
MAINTENANCE["TIREPRESSURE_REARRIGHT"] = 312
MAINTENANCE["TIREPRESSURESTATUS_FRONTLEFT"] = 313
MAINTENANCE["TIREPRESSURESTATUS_FRONTRIGHT"] = 314
MAINTENANCE["TIREPRESSURESTATUS_REARLEFT"] = 315
MAINTENANCE["TIREPRESSURESTATUS_REARRIGHT"] = 316

# PersonalizationEvent (4xx)
PERSONALIZATION = {}
PERSONALIZATION["KEYID"] = 401
PERSONALIZATION["LANGUAGE"] = 402
PERSONALIZATION["MEASUREMENTSYSTEM"] = 403
PERSONALIZATION["MEASUREMENTSYSTEMSTRING_FUEL"] = 404
PERSONALIZATION["MEASUREMENTSYSTEMSTRING_DISTANCE"] = 405
PERSONALIZATION["MEASUREMENTSYSTEMSTRING_SPEED"] = 406
PERSONALIZATION["MEASUREMENTSYSTEMSTRING_CONSUMPTION"] = 407
PERSONALIZATION["MIRROR_DRIVER"] = 408
PERSONALIZATION["MIRROR_PASSENGER"] = 409
PERSONALIZATION["MIRROR_INSIDE"] = 410
PERSONALIZATION["STEERINGWHEELPOSITION_SLIDE"] = 411
PERSONALIZATION["STEERINGWHEELPOSITION_TILT"] = 412
PERSONALIZATION["DRIVINGMODE"] = 413
PERSONALIZATION["DRIVERSEATPOSITION_RECLINESEATBACK"] = 414
PERSONALIZATION["DRIVERSEATPOSITION_SLIDE"] = 415
PERSONALIZATION["DRIVERSEATPOSITION_CUSHIONHEIGHT"] = 416
PERSONALIZATION["DRIVERSEATPOSITION_HEADREST"] = 417
PERSONALIZATION["DRIVERSEATPOSITION_BACKCUSHION"] = 418
PERSONALIZATION["DRIVERSEATPOSITION_SIDECUSHION"] = 419
PERSONALIZATION["PASSENGERSEATPOSITION_RECLINESEATBACK"] = 420
PERSONALIZATION["PASSENGERSEATPOSITION_SLIDE"] = 421
PERSONALIZATION["PASSENGERSEATPOSITION_CUSHIONHEIGHT"] = 422
PERSONALIZATION["PASSENGERSEATPOSITION_HEADREST"] = 423
PERSONALIZATION["PASSENGERSEATPOSITION_BACKCUSHION"] = 424
PERSONALIZATION["PASSENGERSEATPOSITION_SIDECUSHION"] = 425
PERSONALIZATION["DASHBOARDILLUMINATION"] = 426
PERSONALIZATION["GENERATEDVEHICLESOUNDMODE"] = 427

# DrivingSafetyEvent (5xx)
DRIVINGSAFETY = {}
DRIVINGSAFETY["ANTILOCKBRAKINGSYSTEM"] = 501
DRIVINGSAFETY["TRACTIONCONTROLSYSTEM"] = 502
DRIVINGSAFETY["ELECTRONICSTABILITYCONTROL"] = 503
DRIVINGSAFETY["VEHICLETOPSPEEDLIMIT"] = 504
DRIVINGSAFETY["AIRBAGSTATUS_DRIVER"] = 505
DRIVINGSAFETY["AIRBAGSTATUS_PASSENGER"] = 506
DRIVINGSAFETY["AIRBAGSTATUS_SIDE"] = 507
DRIVINGSAFETY["DOOROPENSTATUS_DRIVER"] = 508
DRIVINGSAFETY["DOOROPENSTATUS_PASSENGER"] = 509
DRIVINGSAFETY["DOOROPENSTATUS_REARLEFT"] = 510
DRIVINGSAFETY["DOOROPENSTATUS_REARRIGHT"] = 511
DRIVINGSAFETY["DOOROPENSTATUS_TRUNK"] = 512
DRIVINGSAFETY["DOOROPENSTATUS_FUELFILTERCAP"] = 513
DRIVINGSAFETY["DOOROPENSTATUS_HOOD"] = 514
DRIVINGSAFETY["DOORLOCKSTATUS_DRIVER"] = 515
DRIVINGSAFETY["DOORLOCKSTATUS_PASSENGER"] = 516
DRIVINGSAFETY["DOORLOCKSTATUS_REARLEFT"] = 517
DRIVINGSAFETY["DOORLOCKSTATUS_REARRIGHT"] = 518
DRIVINGSAFETY["CHILDSAFETYLOCK"] = 519
DRIVINGSAFETY["OCCUPANTSSTATUS_DRIVER"] = 520
DRIVINGSAFETY["OCCUPANTSSTATUS_PASSENGER"] = 521
DRIVINGSAFETY["OCCUPANTSSTATUS_REARLEFT"] = 522
DRIVINGSAFETY["OCCUPANTSSTATUS_REARRIGHT"] = 523
DRIVINGSAFETY["SEATBELT_DRIVER"] = 524
DRIVINGSAFETY["SEATBELT_PASSENGER"] = 525
DRIVINGSAFETY["SEATBELT_REARLEFT"] = 526
DRIVINGSAFETY["SEATBELT_REARRIGHT"] = 527
DRIVINGSAFETY["WINDOWLOCK_DRIVER"] = 528
DRIVINGSAFETY["WINDOWLOCK_PASSENGER"] = 529
DRIVINGSAFETY["WINDOWLOCK_REARLEFT"] = 530
DRIVINGSAFETY["WINDOWLOCK_REARRIGHT"] = 531
DRIVINGSAFETY["OBSTACLEDISTANCE_SENSORSTATUS"] = 532
DRIVINGSAFETY["OBSTACLEDISTANCE_FRONTCENTER"] = 533
DRIVINGSAFETY["OBSTACLEDISTANCE_REARCENTER"] = 534
DRIVINGSAFETY["OBSTACLEDISTANCE_FRONTLEFT"] = 535
DRIVINGSAFETY["OBSTACLEDISTANCE_FRONTRIGHT"] = 536
DRIVINGSAFETY["OBSTACLEDISTANCE_MIDDLELEFT"] = 537
DRIVINGSAFETY["OBSTACLEDISTANCE_MIDDLERIGHT"] = 538
DRIVINGSAFETY["OBSTACLEDISTANCE_REARLEFT"] = 539
DRIVINGSAFETY["OBSTACLEDISTANCE_REARRIGHT"] = 540
DRIVINGSAFETY["FRONTCOLLISIONDETECTION_STATUS"] = 541
DRIVINGSAFETY["FRONTCOLLISIONDETECTION_DISTANCE"] = 542
DRIVINGSAFETY["FRONTCOLLISIONDETECTION_TIME"] = 543

# VisionSystemEvent (6xx)
VISIONSYSTEM = {}
VISIONSYSTEM["LANEDEPARTUREDETECTIONSTATUS"] = 601
VISIONSYSTEM["LANEDEPARTED"] = 602

# ParkingEvent (7xx)
PARKING = {}
PARKING["SECURITYALERT"] = 701
PARKING["PARKINGBRAKE"] = 702
PARKING["PARKINGLIGHTS"] = 703

# ClimateEnvironmentEvent (8xx)
CLIMATEENVIRONMENT = {}
CLIMATEENVIRONMENT["INTERIORTEMP"] = 801
CLIMATEENVIRONMENT["EXTERIORTEMP"] = 802
CLIMATEENVIRONMENT["EXTERIORBRIGHTNESS"] = 803
CLIMATEENVIRONMENT["RAINSENSOR"] = 804
CLIMATEENVIRONMENT["WINDSHIELDWIPER"] = 805
CLIMATEENVIRONMENT["REARWIPER"] = 806
CLIMATEENVIRONMENT["HVACFAN_DIRECTION"] = 807
CLIMATEENVIRONMENT["HVACFAN_SPEED"] = 808
CLIMATEENVIRONMENT["HVACFAN_TARGETTEMP"] = 809
CLIMATEENVIRONMENT["AIRCONDITIONING"] = 810
CLIMATEENVIRONMENT["AIRRECIRCULATION"] = 811
CLIMATEENVIRONMENT["HEATER"] = 812
CLIMATEENVIRONMENT["DEFROST_WINDSHIELD"] = 813
CLIMATEENVIRONMENT["DEFROST_REARWINDOW"] = 814
CLIMATEENVIRONMENT["DEFROST_SIDEMIRRORS"] = 815
CLIMATEENVIRONMENT["STEERINGWHEELHEATER"] = 816
CLIMATEENVIRONMENT["SEATHEATER"] = 817
CLIMATEENVIRONMENT["SEATCOOLER"] = 818
CLIMATEENVIRONMENT["WINDOW_DRIVER"] = 819
CLIMATEENVIRONMENT["WINDOW_PASSENGER"] = 820
CLIMATEENVIRONMENT["WINDOW_REARLEFT"] = 821
CLIMATEENVIRONMENT["WINDOW_REARRIGHT"] = 822
CLIMATEENVIRONMENT["SUNROOF_OPENNESS"] = 823
CLIMATEENVIRONMENT["SUNROOF_TILT"] = 824
CLIMATEENVIRONMENT["CONVERTIBLEROOF"] = 825

VehicleEvent = {
    "VEHICLEINFO"        : VEHICLEINFO,
    "RUNNINGSTATUS"      : RUNNINGSTATUS,
    "MAINTENANCE"        : MAINTENANCE,
    "PERSONALIZATION"    : PERSONALIZATION,
    "DRIVINGSAFETY"      : DRIVINGSAFETY,
    "VISIONSYSTEM"       : VISIONSYSTEM,
    "PARKING"            : PARKING,
    "CLIMATEENVIRONMENT" : CLIMATEENVIRONMENT,
}

def vehicle_event_type(header):
    k = int(header)
    for group in VehicleEvent:
        groupdict = VehicleEvent[group]
        for key in groupdict:
            if groupdict[key] == k:
                return group, key
    return None, None
            

VEB = None

class VehicleEventBroker (objects.DBusObject):
    iface = DBusInterface( 'com.windriver.VehicleEventBroker',
                           Signal('vehicleSpeedChanged', 'u')
                         )

    dbusInterfaces = [iface]

    def __init__(self, objectPath):
        objects.DBusObject.__init__(self, objectPath)
        self.speed = 0
        self.direction = 1


    def sendTick(self):
        self.emitSignal('vehicleSpeedChanged', self.speed)
        self.speed += 1 * self.direction
        if self.speed >= 200:
            self.direction = -1
        elif self.speed <= 0:
            self.direction = 1

        #reactor.callLater(0.1, self.sendTick)

def onErr(err):
    print 'Failed: ', err.getErrorMessage()
    #reactor.stop()

def onConnected(conn):
    s = VehicleEventBroker('/VehicleEventBroker')
    conn.exportObject( s )
    dn = conn.requestBusName('org.windriver.automotive')
    def onReady(_):
        global VEB
        VEB = s
    dn.addCallback( onReady )
    return dn




class GeniviVNA(DatagramProtocol):
    def datagramReceived(self, datagram, address):
        header = datagram[:3]
        value = datagram[3:]
        group, key =  vehicle_event_type(header)
        if not group:
            return
        print group, key, value
        VEB.sendTick()

def initGeniviVNA(reactor):
    reactor.listenUDP(5050, GeniviVNA())

    # dbus server for vehicle api
    dconnect = client.connect(reactor)
    dconnect.addCallback(onConnected)
    dconnect.addErrback(onErr)

# vim: sw=4 ts=8 sts=4 et bs=2 fdm=marker fileencoding=utf8
