#!/bin/sh
cd `dirname $0`

PYEXEC=wr-amb.py
PYCEXEC=
PROGRAM=wr_amb.pyc
if [ -f wr_amb.py ]; then
	PROGRAM=wr_amb.py
fi

if [ -f /opt/windriver/lib/libwrs-ipod-2.so ]; then
	LD_LIBRARY_PATH=/opt/windriver/lib/libwrs-ipod-2.so
fi

exec python $PROGRAM
