.pragma library
/* XXX THIS FILE WAS GENERATED BY USING config-default.js AND
config-YOURTARGETDEVICE.js IN CONFIGURATION TIME */

/*
 * Copyright © 2016 Wind River Systems, Inc.
 *
 * The right to copy, distribute, modify, or otherwise make use of this
 * software may be licensed only pursuant to the terms of an applicable
 * Wind River license agreement.
 */

// DEFAULT CONFIG VARIABLES
var displayWidth = 0;
var displayHeight = 0;
var statusBarHeight = 0;
var useMultiWindowFeature = false;
var useMultiWaylandDisplayFeature = false;
var densityAdjust = 1.0;
var useWebEngine = 0;

// XXX OVERWRITE DEFAULT CONFIGs FROM HERE
