.pragma library
/* XXX THIS FILE WAS GENERATED BY USING config-default.js AND
config-YOURTARGETDEVICE.js IN CONFIGURATION TIME */

/*
 * Copyright © 2016 Wind River Systems, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// DEFAULT CONFIG VARIABLES
var displayWidth = 0;
var displayHeight = 0;
var densityAdjust = 1.0;
var useWebEngine = 0;

var objectList = new Array();
var object = function (name, id) {
    this.name = name;
    this.id = id;
}

function registerObjectItem(name, id) {
    var newObject = new object(name, id);
    objectList.push(newObject);
}

function findObjectIdByName(name) {
    for (var index = 0; index < objectList.length; index++) {
        var object = objectList[index];
        if (object.name == name) {
            return object.id;
        }
    }
    return null;
}

// XXX OVERWRITE DEFAULT CONFIGs FROM HERE
