#ifndef WRSIVIPLATFORMCONSTANTS_H
#define WRSIVIPLATFORMCONSTANTS_H

#define WRS_IVI_ID_SURFACE_DEFAULT          0
#define WRS_IVI_ID_SURFACE_NAVIGATION       1
#define WRS_IVI_ID_SURFACE_DIALOG           3
#define WRS_IVI_ID_SURFACE_PHONE            4
#define WRS_IVI_ID_SURFACE_PROJECTION       5
#define WRS_IVI_ID_SURFACE_CAMERA           6

#endif // WRSIVIPLATFORMCONSTANTS_H
