#!/bin/sh
#
#
# Copyright © 2016 Wind River Systems, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

DEVICE=
JSON_OUTPUT=$XDG_RUNTIME_DIR/qt5_eglfs_kms.json

for card in `ls -d /sys/class/drm/card0/card0-*`
do
    if [ $(cat $card/enabled) = 'enabled' ] && [ $(cat $card/status) = 'connected' ]; then
        number=`echo ${card##*-}`
        var=`echo ${card##*/} | awk -F "-" '{print $1,$2}'`

        set -- $var
        connector=$2
		if [ "$DEVICE" = "" ]; then
        	DEVICE=$1
cat <<EOF > $JSON_OUTPUT
{
    "device": "/dev/dri/$DEVICE",
    "hwcursor": false,
    "pbuffers": true,
    "outputs": [
EOF
		fi

        name=${connector}${number}
        modes=`cat $card/modes | awk 'NR==1 {print;exit}'`
cat <<EOF >> $JSON_OUTPUT
		{
			"name": "$name",
			"mode": "$modes"
		},
EOF
    fi
done

echo "	]" >> $JSON_OUTPUT
echo "}" >> $JSON_OUTPUT


echo "Json conf for Qt5 eglfs-kms backend has been generated"
echo "$JSON_OUTPUT:"
cat $JSON_OUTPUT
