/**
 * Copyright (C) 2013, LG Electronics
 *
 * This file is part of GENIVI Project web-api-vehicle.
 *
 * Contributions are licensed to the GENIVI Alliance under one or more
 * Contribution License Agreements.
 *
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Joonhyung Kim <joonhg.kim@lge.com>
 *
 * @file def-socket.h 
 * For further information, see http://www.genivi.org/
 */

#ifndef H_DefSocket
#define H_DefSocket

namespace genivi
{
	namespace wavd
	{
		namespace socket
		{
			/* VehicleInfoEvent (1xx) */
			const int VEHICLEINFO_WMI = 101;
			const int VEHICLEINFO_VIN = 102;
			const int VEHICLEINFO_VEHICLETYPE = 103;
			const int VEHICLEINFO_DOORTYPE_1STROW = 104;
			const int VEHICLEINFO_DOORTYPE_2NDROW = 105;
			const int VEHICLEINFO_DOORTYPE_3RDROW = 106;
			const int VEHICLEINFO_FUELTYPE = 107;
			const int VEHICLEINFO_TRANSMISSIONGEARTYPE = 108;
			const int VEHICLEINFO_WHEELINFO_RADIUS = 109;
			const int VEHICLEINFO_WHEELINFO_TRACK = 110;

			/* RunningStatusEvent (2xx) */
			const int RUNNINGSTATUS_VEHICLEPOWERMODE = 201;
			const int RUNNINGSTATUS_SPEEDOMETER = 202;
			const int RUNNINGSTATUS_ENGINESPEED = 203;
			const int RUNNINGSTATUS_TRIPMETER_1_MILEAGE = 204;
			const int RUNNINGSTATUS_TRIPMETER_2_MILEAGE = 205;
			const int RUNNINGSTATUS_TRIPMETER_1_AVERAGESPEED = 206;
			const int RUNNINGSTATUS_TRIPMETER_2_AVERAGESPEED = 207;
			const int RUNNINGSTATUS_TRIPMETER_1_FUELCONSUMPTION = 208;
			const int RUNNINGSTATUS_TRIPMETER_2_FUELCONSUMPTION = 209;
			const int RUNNINGSTATUS_TRANSMISSIONGEARSTATUS = 210;
			const int RUNNINGSTATUS_CRUISECONTROL_STATUS = 211;
			const int RUNNINGSTATUS_CRUISECONTROL_SPEED = 212;
			const int RUNNINGSTATUS_WHEELBRAKE = 213;
			const int RUNNINGSTATUS_LIGHTSSTATUS_HEAD = 214;
			const int RUNNINGSTATUS_LIGHTSSTATUS_HIGHBEAM = 215;
			const int RUNNINGSTATUS_LIGHTSSTATUS_TURNLEFT = 216;
			const int RUNNINGSTATUS_LIGHTSSTATUS_TURNRIGHT = 217;
			const int RUNNINGSTATUS_LIGHTSSTATUS_BRAKE = 218;
			const int RUNNINGSTATUS_LIGHTSSTATUS_FOGFRONT = 219;
			const int RUNNINGSTATUS_LIGHTSSTATUS_FOGREAR = 220;
			const int RUNNINGSTATUS_LIGHTSSTATUS_HAZARD = 221;
			const int RUNNINGSTATUS_LIGHTSSTATUS_PARKING = 222;
			const int RUNNINGSTATUS_INTERIORLIGHTSSTATUS_DRIVER = 223;
			const int RUNNINGSTATUS_INTERIORLIGHTSSTATUS_PASSENGER = 224;
			const int RUNNINGSTATUS_INTERIORLIGHTSSTATUS_CENTER = 225;
			const int RUNNINGSTATUS_AUTOMATICHEADLIGHTS = 226;
			const int RUNNINGSTATUS_DYNAMICHIGHBEAM = 227;
			const int RUNNINGSTATUS_HORN = 228;
			const int RUNNINGSTATUS_CHIME = 229;
			const int RUNNINGSTATUS_FUEL = 230;
			const int RUNNINGSTATUS_ESTIMATEDRANGE = 231;
			const int RUNNINGSTATUS_ENGINEOIL_REMAINING = 232;
			const int RUNNINGSTATUS_ENGINEOIL_CHANGE = 233;
			const int RUNNINGSTATUS_ENGINEOIL_TEMP = 234;
			const int RUNNINGSTATUS_ENGINECOOLANT_LEVEL = 235;
			const int RUNNINGSTATUS_ENGINECOOLANT_TEMP = 236;
			const int RUNNINGSTATUS_STEERINGWHEELANGLE = 237;

			/* MaintenanceEvent (3xx) */
			const int MAINTENANCE_ODOMETER = 301;
			const int MAINTENANCE_TRANSMISSIONOIL_LIFELEVEL = 302;
			const int MAINTENANCE_TRANSMISSIONOIL_TEMP = 303;
			const int MAINTENANCE_BRAKEFLUIDLEVEL = 304;
			const int MAINTENANCE_WASHERFLUIDLEVEL = 305;
			const int MAINTENANCE_MALFUNCTIONINDICATORLAMP = 306;
			const int MAINTENANCE_BATTERY_VOLTAGE = 307;
			const int MAINTENANCE_BATTERY_CURRENT = 308;
			const int MAINTENANCE_TIREPRESSURE_FRONTLEFT = 309;
			const int MAINTENANCE_TIREPRESSURE_FRONTRIGHT = 310;
			const int MAINTENANCE_TIREPRESSURE_REARLEFT = 311;
			const int MAINTENANCE_TIREPRESSURE_REARRIGHT = 312;
			const int MAINTENANCE_TIREPRESSURESTATUS_FRONTLEFT = 313;
			const int MAINTENANCE_TIREPRESSURESTATUS_FRONTRIGHT = 314;
			const int MAINTENANCE_TIREPRESSURESTATUS_REARLEFT = 315;
			const int MAINTENANCE_TIREPRESSURESTATUS_REARRIGHT = 316;

			/* PersonalizationEvent (4xx) */
			const int PERSONALIZATION_KEYID = 401;
			const int PERSONALIZATION_LANGUAGE = 402;
			const int PERSONALIZATION_MEASUREMENTSYSTEM = 403;
			const int PERSONALIZATION_MEASUREMENTSYSTEMSTRING_FUEL = 404;
			const int PERSONALIZATION_MEASUREMENTSYSTEMSTRING_DISTANCE = 405;
			const int PERSONALIZATION_MEASUREMENTSYSTEMSTRING_SPEED = 406;
			const int PERSONALIZATION_MEASUREMENTSYSTEMSTRING_CONSUMPTION = 407;
			const int PERSONALIZATION_MIRROR_DRIVER = 408;
			const int PERSONALIZATION_MIRROR_PASSENGER = 409;
			const int PERSONALIZATION_MIRROR_INSIDE = 410;
			const int PERSONALIZATION_STEERINGWHEELPOSITION_SLIDE = 411;
			const int PERSONALIZATION_STEERINGWHEELPOSITION_TILT = 412;
			const int PERSONALIZATION_DRIVINGMODE = 413;
			const int PERSONALIZATION_DRIVERSEATPOSITION_RECLINESEATBACK = 414;
			const int PERSONALIZATION_DRIVERSEATPOSITION_SLIDE = 415;
			const int PERSONALIZATION_DRIVERSEATPOSITION_CUSHIONHEIGHT = 416;
			const int PERSONALIZATION_DRIVERSEATPOSITION_HEADREST = 417;
			const int PERSONALIZATION_DRIVERSEATPOSITION_BACKCUSHION = 418;
			const int PERSONALIZATION_DRIVERSEATPOSITION_SIDECUSHION = 419;
			const int PERSONALIZATION_PASSENGERSEATPOSITION_RECLINESEATBACK = 420;
			const int PERSONALIZATION_PASSENGERSEATPOSITION_SLIDE = 421;
			const int PERSONALIZATION_PASSENGERSEATPOSITION_CUSHIONHEIGHT = 422;
			const int PERSONALIZATION_PASSENGERSEATPOSITION_HEADREST = 423;
			const int PERSONALIZATION_PASSENGERSEATPOSITION_BACKCUSHION = 424;
			const int PERSONALIZATION_PASSENGERSEATPOSITION_SIDECUSHION = 425;
			const int PERSONALIZATION_DASHBOARDILLUMINATION = 426;
			const int PERSONALIZATION_GENERATEDVEHICLESOUNDMODE = 427;

			/* DrivingSafetyEvent (5xx) */
			const int DRIVINGSAFETY_ANTILOCKBRAKINGSYSTEM = 501;
			const int DRIVINGSAFETY_TRACTIONCONTROLSYSTEM = 502;
			const int DRIVINGSAFETY_ELECTRONICSTABILITYCONTROL = 503;
			const int DRIVINGSAFETY_VEHICLETOPSPEEDLIMIT = 504;
			const int DRIVINGSAFETY_AIRBAGSTATUS_DRIVER = 505;
			const int DRIVINGSAFETY_AIRBAGSTATUS_PASSENGER = 506;
			const int DRIVINGSAFETY_AIRBAGSTATUS_SIDE = 507;
			const int DRIVINGSAFETY_DOOROPENSTATUS_DRIVER = 508;
			const int DRIVINGSAFETY_DOOROPENSTATUS_PASSENGER = 509;
			const int DRIVINGSAFETY_DOOROPENSTATUS_REARLEFT = 510;
			const int DRIVINGSAFETY_DOOROPENSTATUS_REARRIGHT = 511;
			const int DRIVINGSAFETY_DOOROPENSTATUS_TRUNK = 512;
			const int DRIVINGSAFETY_DOOROPENSTATUS_FUELFILTERCAP = 513;
			const int DRIVINGSAFETY_DOOROPENSTATUS_HOOD = 514;
			const int DRIVINGSAFETY_DOORLOCKSTATUS_DRIVER = 515;
			const int DRIVINGSAFETY_DOORLOCKSTATUS_PASSENGER = 516;
			const int DRIVINGSAFETY_DOORLOCKSTATUS_REARLEFT = 517;
			const int DRIVINGSAFETY_DOORLOCKSTATUS_REARRIGHT = 518;
			const int DRIVINGSAFETY_CHILDSAFETYLOCK = 519;
			const int DRIVINGSAFETY_OCCUPANTSSTATUS_DRIVER = 520;
			const int DRIVINGSAFETY_OCCUPANTSSTATUS_PASSENGER = 521;
			const int DRIVINGSAFETY_OCCUPANTSSTATUS_REARLEFT = 522;
			const int DRIVINGSAFETY_OCCUPANTSSTATUS_REARRIGHT = 523;
			const int DRIVINGSAFETY_SEATBELT_DRIVER = 524;
			const int DRIVINGSAFETY_SEATBELT_PASSENGER = 525;
			const int DRIVINGSAFETY_SEATBELT_REARLEFT = 526;
			const int DRIVINGSAFETY_SEATBELT_REARRIGHT = 527;
			const int DRIVINGSAFETY_WINDOWLOCK_DRIVER = 528;
			const int DRIVINGSAFETY_WINDOWLOCK_PASSENGER = 529;
			const int DRIVINGSAFETY_WINDOWLOCK_REARLEFT = 530;
			const int DRIVINGSAFETY_WINDOWLOCK_REARRIGHT = 531;
			const int DRIVINGSAFETY_OBSTACLEDISTANCE_SENSORSTATUS = 532;
			const int DRIVINGSAFETY_OBSTACLEDISTANCE_FRONTCENTER = 533;
			const int DRIVINGSAFETY_OBSTACLEDISTANCE_REARCENTER = 534;
			const int DRIVINGSAFETY_OBSTACLEDISTANCE_FRONTLEFT = 535;
			const int DRIVINGSAFETY_OBSTACLEDISTANCE_FRONTRIGHT = 536;
			const int DRIVINGSAFETY_OBSTACLEDISTANCE_MIDDLELEFT = 537;
			const int DRIVINGSAFETY_OBSTACLEDISTANCE_MIDDLERIGHT = 538;
			const int DRIVINGSAFETY_OBSTACLEDISTANCE_REARLEFT = 539;
			const int DRIVINGSAFETY_OBSTACLEDISTANCE_REARRIGHT = 540;
			const int DRIVINGSAFETY_FRONTCOLLISIONDETECTION_STATUS = 541;
			const int DRIVINGSAFETY_FRONTCOLLISIONDETECTION_DISTANCE = 542;
			const int DRIVINGSAFETY_FRONTCOLLISIONDETECTION_TIME = 543;

			/* VisionSystemEvent (6xx) */
			const int VISIONSYSTEM_LANEDEPARTUREDETECTIONSTATUS = 601;
			const int VISIONSYSTEM_LANEDEPARTED = 602;

			/* ParkingEvent (7xx) */
			const int PARKING_SECURITYALERT = 701;
			const int PARKING_PARKINGBRAKE = 702;
			const int PARKING_PARKINGLIGHTS = 703;

			/* ClimateEnvironmentEvent (8xx) */
			const int CLIMATEENVIRONMENT_INTERIORTEMP = 801;
			const int CLIMATEENVIRONMENT_EXTERIORTEMP = 802;
			const int CLIMATEENVIRONMENT_EXTERIORBRIGHTNESS = 803;
			const int CLIMATEENVIRONMENT_RAINSENSOR = 804;
			const int CLIMATEENVIRONMENT_WINDSHIELDWIPER = 805;
			const int CLIMATEENVIRONMENT_REARWIPER = 806;
			const int CLIMATEENVIRONMENT_HVACFAN_DIRECTION = 807;
			const int CLIMATEENVIRONMENT_HVACFAN_SPEED = 808;
			const int CLIMATEENVIRONMENT_HVACFAN_TARGETTEMP = 809;
			const int CLIMATEENVIRONMENT_AIRCONDITIONING = 810;
			const int CLIMATEENVIRONMENT_AIRRECIRCULATION = 811;
			const int CLIMATEENVIRONMENT_HEATER = 812;
			const int CLIMATEENVIRONMENT_DEFROST_WINDSHIELD = 813;
			const int CLIMATEENVIRONMENT_DEFROST_REARWINDOW = 814;
			const int CLIMATEENVIRONMENT_DEFROST_SIDEMIRRORS = 815;
			const int CLIMATEENVIRONMENT_STEERINGWHEELHEATER = 816;
			const int CLIMATEENVIRONMENT_SEATHEATER = 817;
			const int CLIMATEENVIRONMENT_SEATCOOLER = 818;
			const int CLIMATEENVIRONMENT_WINDOW_DRIVER = 819;
			const int CLIMATEENVIRONMENT_WINDOW_PASSENGER = 820;
			const int CLIMATEENVIRONMENT_WINDOW_REARLEFT = 821;
			const int CLIMATEENVIRONMENT_WINDOW_REARRIGHT = 822;
			const int CLIMATEENVIRONMENT_SUNROOF_OPENNESS = 823;
			const int CLIMATEENVIRONMENT_SUNROOF_TILT = 824;
			const int CLIMATEENVIRONMENT_CONVERTIBLEROOF = 825;
		}
	}
}

#endif // H_DefSocket
